nodeLinker: node-modules

npmScopes:
  telnyx:
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  sip.js@*:
    peerDependenciesMeta:
      typescript:
        optional: true

yarnPath: .yarn/releases/yarn-4.11.0.cjs
